# Generated by Django 4.2.7 on 2023-11-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=50, unique=True)),
                ('race', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('is_magical', models.BooleanField(default=False)),
                ('char_img', models.ImageField(null=True, upload_to='character_images/')),
            ],
        ),
    ]
