# Generated by Django 4.2.7 on 2023-11-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0003_alter_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.CharField(choices=[('Adeptus Mechanicus', 'Adeptus Mechanicus'), ('Imperial Guard', 'Imperial Guard'), ('Space Marines', 'Space Marines')], default='Space Marines', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
